name: Build

on:
  push:
    branches: [dev]
  pull_request:
  schedule:
    # every Friday at 6:00 UTC
    - cron: "0 6 * * 5"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    strategy:
      fail-fast: false
      matrix:
        config:
          - tests/test-arduino.yaml
          - tests/test-esp-idf.yaml
        esphome-version: [stable, beta, dev]
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: |
            ~/.platformio
            ~/.cache
          key: esphome-${{ matrix.esphome-version }}-${{ matrix.config }}-${{ hashFiles('components/**', 'tests/**') }}
          restore-keys: |
            esphome-${{ matrix.esphome-version }}-${{ matrix.config }}-
      - uses: esphome/build-action@4ef4722a2935eac47b7e227fe0e1f8e0f8afcc42 # v7.3.0
        with:
          yaml-file: ${{ matrix.config }}
          version: ${{ matrix.esphome-version }}
